version: '3'
services:
  flask-app:
    build:
      context: .
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo
    networks:
      - mynetwork

networks:
  mynetwork: